### ISSUE TITLE
Return of the experimental changelog - GitHub API edition (And how to implement it!)

### ISSUE THREAD

**Issue by DazedNConfused-** [DazedNConfused-/CDDA-Game-Launcher#14]
References https://github.com/remyroy/CDDA-Game-Launcher/issues/621

**Comment by Inglonias** [comment]
https://github.com/Fris0uman/CDDA-Game-Launcher/pull/6 might be helpful here. Fris just implemented this for their branch.

**Comment by DazedNConfused-** [comment]
> [Fris0uman#6](https://github.com/Fris0uman/CDDA-Game-Launcher/pull/6) might be helpful here. Fris just implemented this for their branch.

This is good stuff! Thanks for the heads-up, I will seek to have it merged on this fork too.
