### ISSUE TITLE
Add this new mod to the repository

### ISSUE THREAD

**Issue by TadhgEomonn** [DazedNConfused-/CDDA-Game-Launcher#22]
* Name: Arcana and Magic Items mod for Cataclysm: Dark Days Ahead
* Url: https://github.com/chaosvolt/cdda-arcana-mod
* Author: chaosvolt
* Homepage: https://github.com/chaosvolt/cdda-arcana-mod
* Mod not found in version: 1.6.3

**Comment by TadhgEomonn** [comment]
Thank you.

**Comment by DazedNConfused-** [comment]
> Thank you.

![image](https://c.tenor.com/5R8S_-ZpuQoAAAAC/michael-scott-wink.gif)
