### ISSUE TITLE
Add an option for the changelog to have a reverse sorting.

### ISSUE THREAD

**Issue by ziroc** [DazedNConfused-/CDDA-Game-Launcher#55]
Please. It is cumbersome to scroll to the bottom of the log every time to check the latest merged PRs.

**Comment by DazedNConfused-** [comment]
Howdy!

I cannot promise this feature will be delivered, as I am merely a steward for this repo's _maintenance_ (although I do merge PRs providing new features if I can attest their working condition).

That's not to say this request shall never be tackled (as I said, PRs are absolutely welcome and encouraged). In the meantime, lets see how much traction this particular feature attracts. Maybe this changelog thing is more aggravating than I think for the majority of users...

**Comment by Rewstyr** [comment]
I have created https://github.com/DazedNConfused-/CDDA-Game-Launcher/pull/57 to add this feature.

**Comment by TadhgEomonn** [comment]
Well done @Rewstyr !

**Comment by ziroc** [comment]
Great. Works as expected :)

**Comment by DazedNConfused-** [comment]
So the feedback seems to indicate this feature has been well received, therefore I shall be closing this ticket.

Thanks again @Rewstyr for your contribution!
