### ISSUE TITLE
Launcher crash on start

### ISSUE THREAD

**Issue by Arcania88** [DazedNConfused-/CDDA-Game-Launcher#65]
* Description: Trying to start the launcher, it's been crashing, and giving me this error. I've tried following the instructions on the download page, going to %LOCALAPPDATA%\CDDA Game Launcher\ to delete config.db, but this has not improved the issue.
* Version: 1.6.7
* OS: Windows-10-10.0.22000-SP0 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'split'
* Traceback:
```
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 1412, in showEvent
    self.refresh_builds()
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 3266, in refresh_builds
    self.refresh_changelog()
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\main.py", line 3292, in refresh_changelog
    body = entry['body'].split('####'),

```

**Comment by SirClarke** [comment]
Also having the same problem

**Comment by Arcania88** [comment]
I don't know if this helps; but the launcher was working fine this morning (10/6/22), and started crashing every time I try to start it in the evening.

**Comment by RundownRhino** [comment]
The crash seems to be due to failing to parse the latest game build's changelog. Hence one workaround is to launch without internet - then it can't retrieve the latest builds and so doesn't crash.

**Comment by RundownRhino** [comment]
If someone wants to get their launcher working before the PR gets merged, go to `<launcher directory>\cddagl\ui\views\main.py` and change line 3292 in the following way:
```diff
-                                        body = entry['body'].split('####'),
+                                        body = (entry['body'] or "").split('####'),
```

**Comment by Jerald-of-Libya** [comment]
Looks like @RundownRhino already has a fix.. but if you don't wanna wait for the repo owner to merge, you can just copy-paste the change from their PR and slap it onto '\cddagl\ui\views\main.py'

You can also just add like 2 lines to skip the bad entry. Should be around line 3292 on the file just like the log says. Works fine for me eitherway.

            #START - COPY THESE 2 LINES######################
            if entry['body'] is None:
                continue
            #END#######################################
            new_entry = changelog_entry(title =entry['title'],
                                        body = entry['body'].split('####'),
                                        node_id =entry['node_id'],
                                        number=entry['number'],
                                        html_url=entry['html_url']
                                        )
                                        
            if new_date in changelog_sorted:
                changelog_sorted[new_date].append(new_entry)
            else:
                changelog_sorted.update({new_date : [new_entry]})

**Comment by RundownRhino** [comment]
The entry is fine except for not having a description, so I wouldn't skip it. Here's how it looks with my PR applied:
![image](https://user-images.githubusercontent.com/52856631/194543537-fec7e987-03b4-4b49-b7ed-532efca9616e.png)

**Comment by Jerald-of-Libya** [comment]
oh. good point.

that's just me being lazy since i don't really try to read the changes too much.

**Comment by Arcania88** [comment]
Thank you, RundownRhino! Your fix has the launcher working again.

This opens up a new question. Will I need to undo this change when something updates in the future?

**Comment by TadhgEomonn** [comment]
@RundownRhino : You have my thanks also.

**Comment by RundownRhino** [comment]
@Arcania88 I'm not entirely sure, but my understanding is that the launcher update process will replace the file entirely.

**Comment by Arcania88** [comment]
@RundownRhino That makes sense. Thanks again for the help.
