### ISSUE TITLE
Automatic experimental release fetching

### ISSUE THREAD

**Issue by nevermarine** [DazedNConfused-/CDDA-Game-Launcher#75]
Hi,

I'm currently trying to write a PKGBUILD for Arch Linux to automatically fetch the latest CDDA experimental source code. As I discovered, daily releases in CleverRaven's repo are built/compressed straight from the master branch and assigned a tag based on its timestamp. As such, it is not trivial to parse via GitHub API, as there are more than 5000 releases of this game, and a simple GET request to GitHub API yields all of them sequentially (which is pretty slow). 

Thus, I wanted to get help from you, as you seemingly solved the problem. Can you explain in a few words, how exactly do you get the latest experimental release link? 

I've browsed your code for some time and have found some clues, but I'm not an experienced Python developer and some bits just don't fall in place. As I understand, the whole thing takes place in [cddagl/ui/views/main.py](https://github.com/DazedNConfused-/CDDA-Game-Launcher/blob/master/cddagl/ui/views/main.py#L1416), and you're getting a release link by GET request using its tag name, but how do you get a tag name in the first place? I've found a piece of code with `re.compile()` and it looks like you're using it to get a release timestamp, but I couldn't find a place where you actually get that release timestamp.

**Comment by DazedNConfused-** [comment]
Howdy,

Assuming this question is still relevant, you would perhaps have better luck asking it to the author himself [remyroy](https://github.com/remyroy). This repo is only for critical maintenance fixes, and my knowledge of the codebase and Python in general is insufficient to give you a detailed answer - not without performing an analysis of the current logic from, arguably, the same starting position you encounter yourself in (looking at foreign code that is).
