### ISSUE TITLE
Unhandled exception: [Incorrect Win64 Version]

### ISSUE THREAD

**Issue by Chessus** [DazedNConfused-/CDDA-Game-Launcher#82]
* Description: [Tried to update to the latest CDDA Launcher]
* Version: 1.6.8
* OS: Windows-8.1-6.3.9600-SP0 (64-bit)
* Type: `<class 'OSError'>`
* Value: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
* Traceback:
```
  File "C:\Program Files (x86)\CDDA Game Launcher\cddagl\ui\views\tabbed.py", line 614, in http_finished
    subprocess.Popen([self.downloaded_file])
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child

```

**Comment by Chessus** [comment]
Solved, tried to update again today and it go removing the previous launcher version and crashed. I just downloaded 1.6.9 from github and no issues there.

**Comment by DazedNConfused-** [comment]
Seems like this one will go down in history as a mystery. Glad it is solved now though!
